# Generated by Django 2.1.1 on 2018-10-22 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='image',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_image',
            field=models.FileField(blank=True, upload_to='blog/accounts/user_image'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='username',
            field=models.TextField(default='', max_length=128),
        ),
    ]
