# Generated by Django 2.1.1 on 2018-10-22 13:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog_app', '0005_auto_20181018_1800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='love',
            new_name='value',
        ),
        migrations.AddField(
            model_name='post',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'post', 'value')},
        ),
    ]
